# Generated by Django 5.2 on 2025-05-19 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
                ('price', models.IntegerField(default=0)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('platform', 'Platform'), ('obstacle', 'Obstacle'), ('background obj', 'Background obj'), ('item', 'Item'), ('enemy', 'Enemy')], default='platform', max_length=255)),
                ('coordinates', models.CharField(default='0,0', max_length=255)),
                ('size', models.CharField(default='1,1', max_length=255)),
                ('image', models.ImageField(default='block_images/default.png', upload_to='block_images/')),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='character_images/default.png', upload_to='character_images/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='database.avatar'),
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_choice', models.BooleanField(default=False)),
                ('stage_number', models.IntegerField(default=1)),
                ('background', models.ImageField(default='dialog_backgrounds/default.png', upload_to='dialog_backgrounds/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='database.character')),
                ('next_dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_dialoges', to='database.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('final_points', models.IntegerField(default=0)),
                ('level_points', models.IntegerField(default=0)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='database.dialog')),
                ('next_dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_dialogues', to='database.dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='level_backgrounds/default.png', upload_to='level_backgrounds/')),
                ('level_number', models.IntegerField()),
                ('block', models.ManyToManyField(to='database.block')),
                ('next_dialog', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='next_dialogs', to='database.dialog')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='next_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='database.level'),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to='database.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
