# Generated by Django 5.2 on 2025-05-19 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_avatar_block_character_customuser_coins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('total_final_points', models.IntegerField(default=0)),
                ('is_level', models.BooleanField(default=False)),
                ('current_phase', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
